spring:
    profiles:
        active: local
    cloud:
        bus:
            enabled: true
            id: my-config-server
        stream:
            kafka:
                binder:
                    zkNodes: localhost:2181
                    brokers: localhost:9092
server:
    port: 8100
        
environment:
    name: local
    
client:
    superpower: bbb
        
management:
    endpoints:
        web:
            exposure:
                include: "*"